In [1]:
import torch 
import torch.nn.functional as F 

In [2]:
h,w=6,6
ksize=3
torch.manual_seed(1)
image=torch.rand(1,1,h,w)

In [3]:
print(f"input image-->{image.shape}\n{image}")

input image-->torch.Size([1, 1, 6, 6])
tensor([[[[0.7576, 0.2793, 0.4031, 0.7347, 0.0293, 0.7999],
          [0.3971, 0.7544, 0.5695, 0.4388, 0.6387, 0.5247],
          [0.6826, 0.3051, 0.4635, 0.4550, 0.5725, 0.4980],
          [0.9371, 0.6556, 0.3138, 0.1980, 0.4162, 0.2843],
          [0.3398, 0.5239, 0.7981, 0.7718, 0.0112, 0.8100],
          [0.6397, 0.9743, 0.8300, 0.0444, 0.0246, 0.2588]]]])


In [4]:

conv_layer=torch.nn.Conv2d(in_channels=1, out_channels=3, kernel_size=ksize, stride=1, padding=0)
t_op=conv_layer(image)
krnl=conv_layer.weight
biases=conv_layer.bias

In [5]:
Func_op=F.conv2d(image,krnl,bias=biases,stride=1,padding=0)

In [6]:
print(f"\nOutput image using torch-->{t_op.shape}\n{t_op}")
print(f"\nOutput image using functional module-->{Func_op.shape}\n{Func_op}")


Output image using torch-->torch.Size([1, 3, 4, 4])
tensor([[[[ 0.7547,  0.4656,  0.3594,  0.7186],
          [ 0.5617,  0.7179,  0.5315,  0.5112],
          [ 0.5165,  0.3959,  0.6457,  0.5841],
          [ 0.6025,  0.8084,  0.7664,  0.1067]],

         [[-0.4061, -0.3738, -0.5582, -0.2306],
          [-0.4776, -0.3709, -0.3968, -0.3768],
          [-0.3171, -0.3115, -0.2908, -0.4730],
          [-0.4118, -0.4459, -0.3618, -0.5565]],

         [[ 0.4015,  0.2539,  0.4177,  0.3974],
          [ 0.2312,  0.3809,  0.3494,  0.4248],
          [ 0.4048,  0.3176,  0.2225,  0.3113],
          [ 0.7809,  0.3476, -0.0883,  0.0801]]]],
       grad_fn=<ConvolutionBackward0>)

Output image using functional module-->torch.Size([1, 3, 4, 4])
tensor([[[[ 0.7547,  0.4656,  0.3594,  0.7186],
          [ 0.5617,  0.7179,  0.5315,  0.5112],
          [ 0.5165,  0.3959,  0.6457,  0.5841],
          [ 0.6025,  0.8084,  0.7664,  0.1067]],

         [[-0.4061, -0.3738, -0.5582, -0.2306],
          [-0.4776