### Q1 Implement convolution operation for a sample image of shape (H=6, W=6, C=1) with a random kernel of size (3,3) using torch.nn.functional.conv2d.


In [1]:
import torch 
#module contains a collection of functions that operate on tensors but are not part of the neural network layers
import torch.nn.functional as F 
#create an image of dimension hxw with 1 channel
#as conv2d expects 4 dimensional tensor as input, we add extra dimension of 1 at index 0
h,w=6,6
image=torch.rand(1,1,h,w) 
print(f"input image-->{image.shape}\n{image}")
ksize=3
kernel=torch.ones(1,1,ksize,ksize)
print(f"kernel-->{kernel.shape}\n{kernel}")
strides=[1,2,3,4,5,6]
pads=[1,2,3,4,5,6]
for s,p in zip(strides,pads):
    op=F.conv2d(image,kernel,stride=s,padding=p)
    if s==1:
        print(f"Output image for stride 1\n{op}")
    print(f"Stride={s} Padding={p} shape={op.shape}")

input image-->torch.Size([1, 1, 6, 6])
tensor([[[[0.6251, 0.6505, 0.4378, 0.1474, 0.5994, 0.9285],
          [0.2749, 0.9148, 0.6964, 0.1909, 0.1309, 0.0587],
          [0.0864, 0.8156, 0.4789, 0.6431, 0.9574, 0.9215],
          [0.7104, 0.8992, 0.9068, 0.9772, 0.7405, 0.0013],
          [0.8443, 0.4295, 0.3696, 0.4196, 0.2801, 0.0865],
          [0.7689, 0.7415, 0.3323, 0.7337, 0.3579, 0.6738]]]])
kernel-->torch.Size([1, 1, 3, 3])
tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])
Output image for stride 1
tensor([[[[2.4652, 3.5994, 3.0377, 2.2027, 2.0557, 1.7174],
          [3.3673, 4.9803, 4.9753, 4.2821, 4.5778, 3.5964],
          [3.7013, 5.7834, 6.5228, 5.7221, 4.6215, 2.8103],
          [3.7854, 5.5407, 5.9394, 5.7732, 5.0273, 2.9874],
          [4.3937, 6.0024, 5.8093, 5.1177, 4.2705, 2.1401],
          [2.7841, 3.4860, 3.0261, 2.4931, 2.5515, 1.3983]]]])
Stride=1 Padding=1 shape=torch.Size([1, 1, 6, 6])
Stride=2 Padding=2 shape=torch.Size([1, 1, 4, 4])


### Q2 Apply torch.nn.Conv2d to the input image of Qn 1 with out-channel=3 and observe the output. Implement the equivalent of torch.nn.Conv2d using the torch.nn.functional.conv2D to get the same output. You may ignore bias.

In [2]:
import torch 
import torch.nn.functional as F 

h,w=6,6
ksize=3
torch.manual_seed(1)
image=torch.rand(1,1,h,w)

print(f"input image-->{image.shape}\n{image}")

conv_layer=torch.nn.Conv2d(in_channels=1, out_channels=3, kernel_size=ksize, stride=1, padding=0)
t_op=conv_layer(image)
krnl=conv_layer.weight
biases=conv_layer.bias

Func_op=F.conv2d(image,krnl,bias=biases,stride=1,padding=0)

print(f"\nOutput image using torch-->{t_op.shape}\n{t_op}")
print(f"\nOutput image using functional module-->{Func_op.shape}\n{Func_op}")

input image-->torch.Size([1, 1, 6, 6])
tensor([[[[0.7576, 0.2793, 0.4031, 0.7347, 0.0293, 0.7999],
          [0.3971, 0.7544, 0.5695, 0.4388, 0.6387, 0.5247],
          [0.6826, 0.3051, 0.4635, 0.4550, 0.5725, 0.4980],
          [0.9371, 0.6556, 0.3138, 0.1980, 0.4162, 0.2843],
          [0.3398, 0.5239, 0.7981, 0.7718, 0.0112, 0.8100],
          [0.6397, 0.9743, 0.8300, 0.0444, 0.0246, 0.2588]]]])

Output image using torch-->torch.Size([1, 3, 4, 4])
tensor([[[[ 0.7547,  0.4656,  0.3594,  0.7186],
          [ 0.5617,  0.7179,  0.5315,  0.5112],
          [ 0.5165,  0.3959,  0.6457,  0.5841],
          [ 0.6025,  0.8084,  0.7664,  0.1067]],

         [[-0.4061, -0.3738, -0.5582, -0.2306],
          [-0.4776, -0.3709, -0.3968, -0.3768],
          [-0.3171, -0.3115, -0.2908, -0.4730],
          [-0.4118, -0.4459, -0.3618, -0.5565]],

         [[ 0.4015,  0.2539,  0.4177,  0.3974],
          [ 0.2312,  0.3809,  0.3494,  0.4248],
          [ 0.4048,  0.3176,  0.2225,  0.3113],
          [ 0

### Q3 Implement CNN for classifying digits in MNIST dataset using PyTorch. Display the classification accuracy in the form of a Confusion matrix. Verify the number of learnable parameters in the model.

### Q4. Modify CNN of Qn. 3 to reduce the number of parameters in the network. Draw a plot of percentage drop in parameters vs accuracy.